--
-- lab-flask
-- Copyright (c) 2024 Hirotoshi FUJIBE
--

-- Role

DROP ROLE IF EXISTS LAB_FLASK_ROLE;
CREATE ROLE LAB_FLASK_ROLE;

-- User

DROP USER IF EXISTS 'LAB_FLASK_USER'@'localhost';
CREATE USER 'LAB_FLASK_USER'@'localhost' IDENTIFIED BY 'Asdf1234' DEFAULT ROLE LAB_FLASK_ROLE;

-- Schema

DROP SCHEMA IF EXISTS LAB_FLASK;
CREATE SCHEMA LAB_FLASK;

-- USER_LIST

CREATE TABLE LAB_FLASK.USER_LIST (
	USER_ID						CHAR(26)		NOT NULL UNIQUE,
	USER_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	PASSWORD_AES				VARCHAR(416)	NOT NULL, 									-- 32
	USER_DESC					VARCHAR(768)	NOT NULL,									-- 128 * 6 = 768
	PRIMARY KEY ( USER_ID, USER_NAME ),
	UNIQUE ( USER_ID )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON LAB_FLASK.USER_LIST TO LAB_FLASK_ROLE;

-- PRODUCT_LIST

CREATE TABLE LAB_FLASK.PRODUCT_LIST (
	PRODUCT_ID					CHAR(26)		NOT NULL UNIQUE,
	PRODUCT_NAME				VARCHAR(32)		NOT NULL UNIQUE,
	PRODUCT_DESC				VARCHAR(768)	NOT NULL,									-- 128 * 6 = 768
	PRIMARY KEY ( PRODUCT_ID, PRODUCT_NAME )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON LAB_FLASK.PRODUCT_LIST TO LAB_FLASK_ROLE;
